name: ROS Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: ros:melodic-ros-base-bionic

    steps:
    - uses: actions/checkout@v2
      with: 
        path: src/ros_best_practices 

    - name: Install Catkin
      run: |
        apt-get update
        apt-get install -y python-catkin-tools

    - name: Build (Release)
      run: |
        sh /opt/ros/melodic/setup.sh
        git clone https://github.com/ros/catkin.git src/catkin
        catkin init
        catkin build --cmake-args -DCMAKE_BUILD_TYPE=Release
        
    - name: Test
      run: catkin run_tests
